[project]
name = "ml-ops"
version = "0.1.0"
description = "my first mlops project"
authors = [
    {name = "sunny"}
]
license = {text = "MODAK"}
requires-python = ">=3.12"
dependencies = [
    "google-cloud-storage (>=3.8.0,<4.0.0)",
    "pandas (>=3.0.0,<4.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "scipy (>=1.17.0,<2.0.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "numpy (>=2.4.2,<3.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "joblib (>=1.5.3,<2.0.0)",
    "kfp (>=2.15.2,<3.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"